name: daily_runs

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      env_to_run:
        description: The environment in which to run the job
        default: 'stg'
        options:
          - prd
          - stg
        required: true
        type: choice

env:
  DBT_PROFILES_DIR: "."

jobs:
  daily_run_stg:
    if: contains(fromJSON('["stg", ""]'), github.event.inputs.env_to_run)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_STG_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - run: |
          gcloud auth activate-service-account dbt-cicd@beyond-basics-stg.iam.gserviceaccount.com --key-file=./service_account.json && \
          gcloud config set project beyond-basics-stg

      - run: pip install -r requirements.txt

      - run: dbt build --target stg
        env:
          DBT_DATASET: "stg"

  daily_run_prd:
    if: contains(fromJSON('["prd", ""]'), github.event.inputs.env_to_run)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          echo "${{ secrets.DBT_CICD_SA_SECRET_KEY_PRD_BASE64_ENCODED }}" | base64 --decode >> ./service_account.json && \
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"

      - run: |
          gcloud auth activate-service-account dbt-cicd@beyond-basics-prd.iam.gserviceaccount.com --key-file=./service_account.json && \
          gcloud config set project beyond-basics-prd

      - run: pip install -r requirements.txt

      - run: dbt build --target prd
        env:
          DBT_DATASET: "prd"
